version: '3'

services:
  db:
    container_name: db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mekki
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_DATABASE_2: manage_leave_work
    networks:
      - mynetwork


  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - mynetwork

networks:
    mynetwork: